### ISSUE TITLE
getTagName 的参数 jml 为 null

### ISSUE THREAD

**Issue by BANG88** [benjycui/jsonml.js#1]
在 `windows` 下面报错:

![1 pic](https://cloud.githubusercontent.com/assets/433259/14451792/589e916e-00bc-11e6-92d3-2075c40ca50b.jpg)

https://github.com/benjycui/jsonml.js/blob/master/lib/utils.js#L68

`windows` 下面才有这个问题,`mac` 下面同样的代码运行没有问题

**Comment by benjycui** [comment]
这个应该不是 jsonml.js 的问题，你是怎么使用 jsonml.js 的？

**Comment by BANG88** [comment]
clone antd 在 windows 下面开发

**Comment by benjycui** [comment]
没 windows 的环境。。你看下对应页面 demo 的数据。

![image](https://cloud.githubusercontent.com/assets/3580607/14549876/65b4841c-02f6-11e6-99c6-d1d4ed50a867.png)

**Comment by benjycui** [comment]
建议先删除 `node_modules` 并重新安装
