### ISSUE TITLE
Open to contribution?

### ISSUE THREAD

**Issue by pgoldrbx** [benjycui/jsonml.js#3]
Hey @benjycui,

I'm using this module in some libraries and applications and it's been helpful. I'd like to contribute back and help with the maintenance of the project. Are you accepting contributions at this time? Where is the best place to begin? It looks like there's a need for complete test coverage, eslint cleanup, and documentation. If you're interested, we could begin opening issues to track this work.

I've gone ahead and opened a few PRs that should help move things along:
- [#4 - Add nyc for coverage reports](https://github.com/benjycui/jsonml.js/pull/4)
- [#5 - Add complete unit tests for utils interface](https://github.com/benjycui/jsonml.js/pull/5)
- [#6 - Cleanup existing lint rules on utils](https://github.com/benjycui/jsonml.js/pull/6)

**Comment by benjycui** [comment]
> I'd like to contribute back and help with the maintenance of the project.

Yep, thanks, you can PR any time, and I will review it when I have time, thanks.

**Comment by pgoldrbx** [comment]
Great! I'll close this question.
